//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CourseApp.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-07/schema#&quot;,
        ///  &quot;title&quot;: &quot;SMERP External APP Connector AppSettgins&quot;,
        ///  &quot;description&quot;: &quot;Defines *SMERP intance* configuration for particula APP connector&quot;,
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;required&quot;: [
        ///    &quot;ConnectionStrings&quot;,   
        ///    &quot;Jwt&quot;
        ///  ],
        ///  &quot;properties&quot;: {
        ///    &quot;ConnectionStrings&quot;: {
        ///      &quot;$ref&quot;: &quot;#/definitions/ConnectionStrings&quot;
        ///    },
        ///    &quot;Jwt&quot;: {
        ///      &quot;$ref&quot;: &quot;#/definitions/Jwt&quot;
        ///    },
        ///    &quot;OAuth&quot;: {
        ///      &quot;$ref&quot;: &quot;#/definitions/OAuth&quot;
        ///    }   
        ///  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string appsettingsSchema_v1_json {
            get {
                return ResourceManager.GetString("appsettingsSchema_v1.json", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {
        ///  &quot;Logging&quot;: {
        ///    &quot;LogLevel&quot;: {
        ///      &quot;Default&quot;: &quot;Information&quot;,
        ///      &quot;Microsoft.AspNetCore&quot;: &quot;Warning&quot;
        ///    }
        ///  },
        ///  &quot;ConnectionStrings&quot;: {
        ///    &quot;MsSqlConnectionString&quot;: &quot;Server=localhost,1433;Database=CoursesDb;User Id=sa;Password=TwojeMocneHasĹ‚o123;Encrypt=False;&quot;
        ///  },
        ///  &quot;Events&quot;: {
        ///    &quot;Context&quot;: &quot;ExampleConnector&quot;,
        ///    &quot;ListenContexts&quot;: [
        ///      {
        ///        &quot;Name&quot;: &quot;own&quot;,
        ///        &quot;Url&quot;: &quot;http://localhost:5277&quot;
        ///      }
        ///    ]
        ///  },
        ///  &quot;Jwt&quot;: {
        ///    &quot;Issuer&quot;: &quot;https://fewfwe.cloud&quot;,
        ///    &quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string projectAppSettings_json {
            get {
                return ResourceManager.GetString("projectAppSettings.json", resourceCulture);
            }
        }
    }
}
